services:
  web:
    build: .
    command: gunicorn threat_monitoring_platform.wsgi:application --bind 0.0.0.0:8010 --workers 3
    ports:
      - "8010:8010"

    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7-alpine

volumes:
  static_volume:
  media_volume:
